"""Builds the tiny launcher EXE (ClipFinder_dist\\ClipFinder.exe): no console window, launches
clipfinder.py with the embedded Python.

The EXE carries a Windows version resource (Explorer -> Properties -> Details) whose number is
read from APP_VERSION in clipfinder.py - the same value tools/release_version.py enforces
against the git tag - so a launcher can never say a different version than the app.
"""
import os
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
os.chdir(HERE)
sys.path.insert(0, str(HERE / 'tools'))
import release_version  # noqa: E402  (single implementation of "read APP_VERSION")

NAME = 'ClipFinder'
COMPANY = 'MarsScumbags'
STUB_FILE = HERE / '_launcher_stub.py'
VERSION_FILE = HERE / '_launcher_version.txt'
BUILD_DIR = HERE / '_launcher_build'

# Raw string: the \n escapes below must reach the generated stub as \n, not as real newlines.
stub = r'''
import subprocess, sys, os, ctypes


def _fail(msg):
    ctypes.windll.user32.MessageBoxW(0, msg, 'ClipFinder', 0x10)   # MB_ICONERROR
    sys.exit(1)


# Frozen (PyInstaller onefile): sys.executable is the path of THIS exe. sys.argv[0] can be a
# bare or relative name depending on how Windows started us, so never derive the folder from it.
if getattr(sys, 'frozen', False):
    app_dir = os.path.dirname(os.path.abspath(sys.executable))
else:
    app_dir = os.path.dirname(os.path.abspath(__file__))
os.chdir(app_dir)
py = os.path.join(app_dir, 'python', 'python.exe')
app = os.path.join(app_dir, 'clipfinder.py')
if not (os.path.exists(py) and os.path.exists(app)):
    _fail('ClipFinder files are missing:\n' + py + '\n' + app + '\n\nPlease reinstall ClipFinder.')
try:
    # Launch with no console window (CREATE_NO_WINDOW = 0x08000000)
    subprocess.Popen([py, app], cwd=app_dir, creationflags=0x08000000)
except OSError as e:
    _fail('ClipFinder could not be started:\n' + str(e))
'''


def version_file_text(ver: str) -> str:
    """PyInstaller --version-file content (VSVersionInfo) for X.Y.Z.W."""
    a, b, c, d = (int(x) for x in ver.split('.'))
    return f'''# UTF-8
# Generated by build_launcher.py from APP_VERSION in clipfinder.py - do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({a}, {b}, {c}, {d}),
    prodvers=({a}, {b}, {c}, {d}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName', '{COMPANY}'),
        StringStruct('FileDescription', '{NAME} Launcher'),
        StringStruct('FileVersion', '{ver}'),
        StringStruct('InternalName', '{NAME}'),
        StringStruct('LegalCopyright', 'Copyright (c) {COMPANY}'),
        StringStruct('OriginalFilename', '{NAME}.exe'),
        StringStruct('ProductName', '{NAME}'),
        StringStruct('ProductVersion', '{ver}')])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
'''


def main() -> int:
    try:
        ver = release_version.read_app_version(HERE)   # raises (asserts found) if missing / not X.Y.Z.W
    except release_version.ReleaseError as e:
        print(f'ERROR: {e}', file=sys.stderr)
        return 1
    print(f'  Launcher version: {ver}')

    STUB_FILE.write_text(stub, encoding='utf-8')
    VERSION_FILE.write_text(version_file_text(ver), encoding='utf-8')
    ico = HERE / 'clipfinder.ico'

    cmd = [
        sys.executable, '-m', 'PyInstaller',
        str(STUB_FILE),
        '--onefile', '--noconsole',
        '--name', NAME,
        '--distpath', 'ClipFinder_dist',
        '--workpath', str(BUILD_DIR),
        '--specpath', str(BUILD_DIR),
        '--version-file', str(VERSION_FILE),
        '--noconfirm', '--clean', '--log-level', 'WARN',
    ]
    if ico.exists():
        cmd += ['--icon', str(ico)]

    try:
        rc = subprocess.run(cmd).returncode
    finally:
        STUB_FILE.unlink(missing_ok=True)
        VERSION_FILE.unlink(missing_ok=True)
        shutil.rmtree(BUILD_DIR, ignore_errors=True)
    if rc == 0 and not (HERE / 'ClipFinder_dist' / f'{NAME}.exe').exists():
        print(f'ERROR: PyInstaller reported success but ClipFinder_dist\\{NAME}.exe is missing', file=sys.stderr)
        return 1
    return rc


if __name__ == '__main__':
    sys.exit(main())
